#!/bin/bash
cd /speech/batch2/sharan/NPTEL-Challenge/NPTEL_ASR_Challenge
. ./path.sh
( echo '#' Running on `hostname`
  echo '#' Started at `date`
  echo -n '# '; cat <<EOF
lattice-align-phones --replace-output-symbols=true exp_hindi_model/chain40hour/tri3_2000_32000_train_sp_lats/final.mdl "ark:gunzip -c exp_hindi_model/chain40hour/tri3_2000_32000_train_sp_lats/lat.$SGE_TASK_ID.gz |" ark:- | chain-get-supervision --lattice-input=true --frame-subsampling-factor=3 --right-tolerance=5 --left-tolerance=5 exp_hindi_model/chain40hour/tdnn1g_sp/tree exp_hindi_model/chain40hour/tdnn1g_sp/0.trans_mdl ark:- ark:- | nnet3-chain-get-egs --online-ivectors=scp:exp_hindi_model/nnet340hour/ivectors_train_sp_hires/ivector_online.scp --online-ivector-period=10 --srand=$[$SGE_TASK_ID+0] --left-context=29 --right-context=29 --num-frames=140,100,160 --frame-subsampling-factor=3 --compress=true --num-frames-overlap=0 "ark,s,cs:utils/filter_scp.pl --exclude exp_hindi_model/chain40hour/tdnn1g_sp/egs/valid_uttlist data_hindi/train_sp_hires/split30/$SGE_TASK_ID/feats.scp | apply-cmvn --norm-means=false --norm-vars=false --utt2spk=ark:data_hindi/train_sp_hires/split30/$SGE_TASK_ID/utt2spk scp:data_hindi/train_sp_hires/split30/$SGE_TASK_ID/cmvn.scp scp:- ark:- |" ark,s,cs:- ark:- | nnet3-chain-copy-egs --random=true --srand=$[$SGE_TASK_ID+0] ark:- ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.1.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.2.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.3.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.4.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.5.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.6.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.7.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.8.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.9.ark 
EOF
) >exp_hindi_model/chain40hour/tdnn1g_sp/egs/log/get_egs.$SGE_TASK_ID.log
 ( lattice-align-phones --replace-output-symbols=true exp_hindi_model/chain40hour/tri3_2000_32000_train_sp_lats/final.mdl "ark:gunzip -c exp_hindi_model/chain40hour/tri3_2000_32000_train_sp_lats/lat.$SGE_TASK_ID.gz |" ark:- | chain-get-supervision --lattice-input=true --frame-subsampling-factor=3 --right-tolerance=5 --left-tolerance=5 exp_hindi_model/chain40hour/tdnn1g_sp/tree exp_hindi_model/chain40hour/tdnn1g_sp/0.trans_mdl ark:- ark:- | nnet3-chain-get-egs --online-ivectors=scp:exp_hindi_model/nnet340hour/ivectors_train_sp_hires/ivector_online.scp --online-ivector-period=10 --srand=$[$SGE_TASK_ID+0] --left-context=29 --right-context=29 --num-frames=140,100,160 --frame-subsampling-factor=3 --compress=true --num-frames-overlap=0 "ark,s,cs:utils/filter_scp.pl --exclude exp_hindi_model/chain40hour/tdnn1g_sp/egs/valid_uttlist data_hindi/train_sp_hires/split30/$SGE_TASK_ID/feats.scp | apply-cmvn --norm-means=false --norm-vars=false --utt2spk=ark:data_hindi/train_sp_hires/split30/$SGE_TASK_ID/utt2spk scp:data_hindi/train_sp_hires/split30/$SGE_TASK_ID/cmvn.scp scp:- ark:- |" ark,s,cs:- ark:- | nnet3-chain-copy-egs --random=true --srand=$[$SGE_TASK_ID+0] ark:- ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.1.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.2.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.3.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.4.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.5.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.6.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.7.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.8.ark ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.$SGE_TASK_ID.9.ark  ) 2>>exp_hindi_model/chain40hour/tdnn1g_sp/egs/log/get_egs.$SGE_TASK_ID.log >>exp_hindi_model/chain40hour/tdnn1g_sp/egs/log/get_egs.$SGE_TASK_ID.log
ret=$?
echo '#' Finished at `date` with status $ret >>exp_hindi_model/chain40hour/tdnn1g_sp/egs/log/get_egs.$SGE_TASK_ID.log
[ $ret -eq 137 ] && exit 100;
touch exp_hindi_model/chain40hour/tdnn1g_sp/egs/q/done.4366.$SGE_TASK_ID
exit $[$ret ? 1 : 0]
## submitted with:
# qsub -q cpu.q -l h="h1|h2|d3|d4|d5|d6|d7" -S /bin/bash -v PATH -cwd -j y -o exp_hindi_model/chain40hour/tdnn1g_sp/egs/q/get_egs.log --max-jobs-run 15  -t 1:30 /speech/batch2/sharan/NPTEL-Challenge/NPTEL_ASR_Challenge/exp_hindi_model/chain40hour/tdnn1g_sp/egs/q/get_egs.sh >>exp_hindi_model/chain40hour/tdnn1g_sp/egs/q/get_egs.log 2>&1
