#!/bin/bash
cd /speech/batch2/sharan/NPTEL-Challenge/NPTEL_ASR_Challenge
. ./path.sh
( echo '#' Running on `hostname`
  echo '#' Started at `date`
  echo -n '# '; cat <<EOF
nnet3-chain-normalize-egs --normalization-fst-scale=1.0 exp_hindi_model/chain40hour/tdnn1g_sp/normalization.fst "ark:cat  exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.1.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.2.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.3.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.4.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.5.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.6.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.7.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.8.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.9.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.10.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.11.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.12.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.13.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.14.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.15.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.16.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.17.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.18.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.19.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.20.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.21.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.22.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.23.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.24.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.25.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.26.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.27.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.28.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.29.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.30.${SGE_TASK_ID}.ark|" ark:- | nnet3-chain-shuffle-egs --srand=$[${SGE_TASK_ID}+0] ark:- ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs.${SGE_TASK_ID}.ark 
EOF
) >exp_hindi_model/chain40hour/tdnn1g_sp/egs/log/shuffle.$SGE_TASK_ID.log
time1=`date +"%s"`
 ( nnet3-chain-normalize-egs --normalization-fst-scale=1.0 exp_hindi_model/chain40hour/tdnn1g_sp/normalization.fst "ark:cat  exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.1.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.2.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.3.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.4.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.5.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.6.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.7.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.8.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.9.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.10.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.11.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.12.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.13.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.14.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.15.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.16.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.17.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.18.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.19.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.20.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.21.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.22.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.23.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.24.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.25.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.26.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.27.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.28.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.29.${SGE_TASK_ID}.ark exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs_orig.30.${SGE_TASK_ID}.ark|" ark:- | nnet3-chain-shuffle-egs --srand=$[${SGE_TASK_ID}+0] ark:- ark:exp_hindi_model/chain40hour/tdnn1g_sp/egs/cegs.${SGE_TASK_ID}.ark  ) 2>>exp_hindi_model/chain40hour/tdnn1g_sp/egs/log/shuffle.$SGE_TASK_ID.log >>exp_hindi_model/chain40hour/tdnn1g_sp/egs/log/shuffle.$SGE_TASK_ID.log
ret=$?
time2=`date +"%s"`
echo '#' Accounting: time=$(($time2-$time1)) threads=1 >>exp_hindi_model/chain40hour/tdnn1g_sp/egs/log/shuffle.$SGE_TASK_ID.log
echo '#' Finished at `date` with status $ret >>exp_hindi_model/chain40hour/tdnn1g_sp/egs/log/shuffle.$SGE_TASK_ID.log
[ $ret -eq 137 ] && exit 100;
touch exp_hindi_model/chain40hour/tdnn1g_sp/egs/q/sync/done.32350.$SGE_TASK_ID
exit $[$ret ? 1 : 0]
## submitted with:
# qsub -v PATH -cwd -S /bin/bash -j y -l arch=*64* -o exp_hindi_model/chain40hour/tdnn1g_sp/egs/q/shuffle.log  -tc 50 -l mem_free=8G  -t 1:9 /speech/batch2/sharan/NPTEL-Challenge/NPTEL_ASR_Challenge/exp_hindi_model/chain40hour/tdnn1g_sp/egs/q/shuffle.sh >>exp_hindi_model/chain40hour/tdnn1g_sp/egs/q/shuffle.log 2>&1
